#!/usr/bin/env node
'use strict';
// Single source of truth: data/reference-data.json.
// This script regenerates everything that is derived from it:
//   python-toolkit/toolkit/reference_data.py
//   js-toolkit/src/utils/referenceData.js and botbench-sdk/src/referenceData.js
//   data/apis.json, data/apis.csv, data/endpoints.csv
//   docs/CHEATSHEET.md, docs/FREE-APIS.md
//   the data block inside website/index.html
// After running it, rebuild the SDK bundle:  (cd botbench-sdk && node build.js)
// Usage: node scripts/generate-data.js

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const at = (...p) => path.join(root, ...p);
const write = (file, text) => { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text); };
const data = JSON.parse(fs.readFileSync(at('data', 'reference-data.json'), 'utf8'));

const KEYS = ['ENDPOINTS', 'OPCODES', 'EVENTS', 'INTENTS', 'PERMS', 'ITYPES', 'SCOPES', 'LIMITS', 'CLOSES', 'ERRORS', 'LIBS', 'TOOLS', 'DOCS', 'APIS', 'PROJECTS'];
for (const k of KEYS) if (!Array.isArray(data[k])) throw new Error(`data/reference-data.json is missing "${k}"`);
const DESC = {
  ENDPOINTS: '[method, path, description]', OPCODES: '[op, name, direction, meaning]', EVENTS: '[event, fires when, needs]',
  INTENTS: '[name, value, gives you, privileged 0/1]', PERMS: '[name, value]', ITYPES: '[kind, value, name]', SCOPES: '[scope, description]',
  LIMITS: '[thing, limit]', CLOSES: '[code, name, what to do]', ERRORS: '[code, meaning, usual fix]', LIBS: '[language, library, install, notes, docs url]',
  TOOLS: '[name, description, url]', DOCS: '[name, description, url]',
  APIS: '[name, type, key, description, url]   key is "None" when no signup is needed', PROJECTS: 'project ideas',
};
const rows = (k, indent) => data[k].map((r) => `${indent}${JSON.stringify(r)},`).join('\n');

// ---- validation: catch mistakes before they spread into three languages
const seen = new Set();
for (const [name, type, key, description, url] of data.APIS) {
  if (!name || !type || !key || !description || !/^https?:\/\//.test(url)) throw new Error(`Bad APIS row: ${name}`);
  if (seen.has(name.toLowerCase())) throw new Error(`Duplicate API name: ${name}`);
  seen.add(name.toLowerCase());
}
for (const [, p] of data.PERMS) if (!/^1 << \d+$/.test(p)) throw new Error(`Bad permission value: ${p}`);

// ---- python
let py = '"""Discord API reference data and the free-API directory.\n\nGenerated by scripts/generate-data.js from data/reference-data.json. Do not edit by hand.\n"""\n\n';
for (const k of KEYS) py += `# ${DESC[k]}\n${k} = [\n${rows(k, '    ')}\n]\n\n`;
write(at('python-toolkit', 'toolkit', 'reference_data.py'), py.trimEnd() + '\n');

// ---- javascript (toolkit + sdk)
let js = "'use strict';\n// Discord API reference data and the free-API directory.\n// Generated by scripts/generate-data.js from data/reference-data.json. Do not edit by hand.\n\n";
for (const k of KEYS) js += `// ${DESC[k]}\nconst ${k} = [\n${rows(k, '  ')}\n];\n\n`;
js += `module.exports = { ${KEYS.join(', ')} };\n`;
write(at('js-toolkit', 'src', 'utils', 'referenceData.js'), js);
write(at('botbench-sdk', 'src', 'referenceData.js'), js);

// ---- data exports
const csv = (v) => `"${String(v).replace(/"/g, '""')}"`;
write(at('data', 'apis.json'), JSON.stringify(data.APIS.map(([name, type, key, description, url]) => ({ name, type, key, description, url })), null, 1) + '\n');
write(at('data', 'apis.csv'), ['name,type,key,description,url', ...data.APIS.map((r) => r.map(csv).join(','))].join('\n') + '\n');
write(at('data', 'endpoints.csv'), ['method,path,description', ...data.ENDPOINTS.map((r) => r.map(csv).join(','))].join('\n') + '\n');

// ---- docs
const esc = (s) => String(s).replace(/\|/g, '\\|');
const table = (head, list, fmt) => `| ${head.join(' | ')} |\n|${head.map(() => '---').join('|')}|\n${list.map((r) => `| ${fmt(r).map(esc).join(' | ')} |`).join('\n')}\n`;
let md = '# Discord bot cheat sheet\n\nGenerated from `data/reference-data.json`. Paths are relative to `https://discord.com/api/v10`.\nCheck https://discord.com/developers/docs for the latest details, since Discord changes its API.\n\n';
md += `## REST endpoints\n\n${table(['Method', 'Path', 'What it does'], data.ENDPOINTS, (r) => [r[0], `\`${r[1]}\``, r[2]])}`;
md += `\n## Gateway opcodes\n\nConnect to \`wss://gateway.discord.gg/?v=10&encoding=json\`.\n\n${table(['Op', 'Name', 'Direction', 'Meaning'], data.OPCODES, (r) => r)}`;
md += `\n## Common gateway events\n\n${table(['Event', 'Fires when', 'Needs'], data.EVENTS, (r) => [`\`${r[0]}\``, r[1], r[2]])}`;
md += `\n## Intents\n\nPrivileged intents must be enabled in the Developer Portal.\n\n${table(['Intent', 'Value', 'Gives you', 'Privileged'], data.INTENTS, (r) => [`\`${r[0]}\``, `\`${r[1]}\``, r[2], r[3] ? 'yes' : ''])}`;
md += `\n## Permissions\n\nValues above 2^31 need 64-bit integers (BigInt in JavaScript).\n\n${table(['Permission', 'Value'], data.PERMS, (r) => [`\`${r[0]}\``, `\`${r[1]}\``])}`;
md += `\n## Interaction and reply types\n\n${table(['Kind', 'Value', 'Name'], data.ITYPES, (r) => [r[0], `\`${r[1]}\``, r[2]])}`;
md += `\n## OAuth2 scopes\n\n${table(['Scope', 'Lets you'], data.SCOPES, (r) => [`\`${r[0]}\``, r[1]])}`;
md += `\n## Limits\n\n${table(['Thing', 'Limit'], data.LIMITS, (r) => r)}`;
md += `\n## Gateway close codes\n\n${table(['Code', 'Name', 'What to do'], data.CLOSES, (r) => [`\`${r[0]}\``, r[1], r[2]])}`;
md += `\n## Error codes\n\n${table(['Code', 'Meaning', 'Usual fix'], data.ERRORS, (r) => [`\`${r[0]}\``, r[1], r[2]])}`;
md += `\n## Libraries\n\n${table(['Language', 'Library', 'Install', 'Notes'], data.LIBS, (r) => [r[0], `[${r[1]}](${r[4]})`, `\`${r[2]}\``, r[3]])}`;
write(at('docs', 'CHEATSHEET.md'), md);

let ap = `# Free APIs for bots (${data.APIS.length})\n\nKey **None** means you can call it without signing up. Free APIs change or shut down: open the URL before you build on it, and read the provider's terms.\n\n`;
for (const t of [...new Set(data.APIS.map((a) => a[1]))].sort()) ap += `## ${t}\n\n${table(['API', 'Key', 'What it does'], data.APIS.filter((a) => a[1] === t), (r) => [`[${r[0]}](${r[4]})`, r[2], r[3]])}\n`;
write(at('docs', 'FREE-APIS.md'), ap);

// ---- the data block inside the website
const sitePath = at('website', 'index.html');
let site = fs.readFileSync(sitePath, 'utf8');
const a = site.indexOf('/* ================= DATA');
const b = site.indexOf('/* ================= HELPERS');
if (a < 0 || b < 0) throw new Error('Could not find the DATA block in website/index.html');
let block = '/* ================= DATA ================= */\n// Generated by scripts/generate-data.js from data/reference-data.json. Edit that file, not this block.\n';
for (const k of KEYS) block += `/* ${DESC[k]} */\nvar ${k}=[\n${rows(k, ' ')}\n];\n`;
write(sitePath, site.slice(0, a) + block + site.slice(b));

console.log(`Generated from data/reference-data.json: ${data.APIS.length} APIs, ${data.ENDPOINTS.length} endpoints, ${data.PERMS.length} permissions.`);
console.log('Now rebuild the SDK bundle:  (cd botbench-sdk && node build.js)');
